### ISSUE TITLE
Link wird nicht erkannt

### ISSUE THREAD

**Issue by juliapradel** [BurdaMagazinOrg/module-thunder_print#37]
Ich habe einen Text aus dem Internet kopiert, ein mitkopierter Link wird im Formular blau angezeigt (auch nachdem das Textformat geändert wurde), das kann ich auch nicht ändern. In der Preview wird das Wort nicht angezeigt.

**Comment by chrfritsch** [comment]
Fixed. Links sind nun nicht mehr erlaubt in dem Textfeld. Sie werden automatisch entfernt beim reinkopieren
