### ISSUE TITLE
Probleme mit Template "1 spaltig kwi"

### ISSUE THREAD

**Issue by juliapradel** [BurdaMagazinOrg/module-thunder_print#38]
- unsinnige Reihenfolge der Formularfelder - Text, dann Lead, dann Bild (warum eigentlich ein Alt-Text für den Druck?!), dann erst Titel
- Zwischenüberschrift ist nach Änderung im Formularfeld nicht sichtbar fett, eher ein bisschen kleiner als der restliche Text
- Am Ende des Leads steht "Lead von", ohne dass ich das im Lead-Formular sehe und ändern kann
- Titel wird in Preview nicht angezeigt

**Comment by chrfritsch** [comment]
1. Reihnfolge lässt sich jederzeit ändern und wurde vom Ersteller des Templates nur nicht angepasst
2. Muss ich schauen
3. Muss ich schauen
4. Der Lead ist so lang das der Titel überlagert wird

**Comment by chrfritsch** [comment]
2. Fixed
3. In diesem Template ist das Lead Feld eigentlich als Volltextfeld vogesehen, nicht als PlainText. Daher kommt es dort zu Problemen
