### ISSUE TITLE
Falsche Preview nach Template-Wechsel

### ISSUE THREAD

**Issue by juliapradel** [BurdaMagazinOrg/module-thunder_print#42]
Ich hatte den Text im Template „1 spaltig kwi“ angelegt und dann das Template gewechselt. Jedes Mal, wenn ich den Artikel zum Bearbeiten öffne, wird zunächst das alte Template (1 spaltig kwi) in der Vorschau angezeigt. Ich muss erst auf „Update quick preview“ klicken, um die Vorschau im richtigen (3 spaltig kwi) Template zu erhalten

**Comment by chrfritsch** [comment]
Fixed
