### ISSUE TITLE
Template-Wechsel nicht sehr komfortabel

### ISSUE THREAD

**Issue by juliapradel** [BurdaMagazinOrg/module-thunder_print#43]
kann nicht rückgängig gemacht werden - wenn man unzufrieden ist und doch lieber die erste Variante hätte, fängt man bei Null an. 

Besonders kritisch, weil es weder eine Warnmeldung noch eine Vorschau gibt - ich weiß also gar nicht genau, wo ich hingehe, oder verklicke mich, und gleich ist die ganze Arbeit dahin...

**Comment by chrfritsch** [comment]
Es wird nun eine Warnung angezeigt und ausserdem ein Preview generiert wenn ein Template ausgewählt wurde
