### ISSUE TITLE
Lead Feld zu klein

### ISSUE THREAD

**Issue by juliapradel** [BurdaMagazinOrg/module-thunder_print#45]
Ich finde, das Lead-Feld ist unpraktikabel klein. Da steht mindestens ein Satz, mitunter auch mehr. Man sieht nicht, was man reingeschrieben hat, und wenn man am Ende des Textes was ändern muss, muss man erst mühselig mit den Pfeiltasten hin.

**Comment by chrfritsch** [comment]
Das ist eine Sache der Konfiguration. In den Tag-Mappings kann konfiguriert werden wie das Widget angezeigt werden soll (admin/structure/thunder_print/tag_mapping/xmltag_lead/edit).
